triggered.exclude = [
  # is mostly just copied from scala stdlib, don't want to change this more than necessary
  "**/OrderStatisticsTree.scala"
]

rules = [
  # start of built-in rules
  OrganizeImports,
  NoValInForComprehension,
  RedundantSyntax,
  RemoveUnused,
  DisableSyntax,
  NoValInForComprehension,
  # end of built-in rules
  # start of Scapegoat rules
   ArrayEquals,
    ArraysInFormat
    ArraysToString
    AsInstanceOf,
    AvoidSizeEqualsZero,
    AvoidSizeNotEqualsZero,
    AvoidToMinusOne,
    BigDecimalDoubleConstructor,
    BigDecimalScaleWithoutRoundingMode,
    BooleanParameter, 
    BoundedByFinalType,
    BrokenOddness,
    CatchException,
    CatchExceptionImmediatelyRethrown,
    CatchFatal,
    CatchNpe,
    CatchThrowable,
    ClassNames,
    # CollectionIndexOnNonIndexedSeq  #also warns when constructing a single-element seq
    CollectionNamingConfusion,
    CollectionNegativeIndex,
    CollectionPromotionToAny,
    ComparingFloatingPointTypes,
    ComparisonToEmptyList,
    ComparisonToEmptySet,
    ComparisonWithSelf,
    ConstantIf,
    DivideByOne,
    DoubleNegation,
    DuplicateImport,
    DuplicateMapKey,
    DuplicateSetValue,
    EitherGet,
    EmptyCaseClass,
    EmptyFor,
    EmptyIfBlock,
    EmptyInterpolatedString,
    EmptyMethod,
    EmptySynchronizedBlock,
    EmptyTryBlock,
    EmptyWhileBlock,
    ExistsSimplifiableToContains
    FilterDotHead,
    FilterDotHeadOption,
    FilterDotIsEmpty,
    FilterDotSize,
    FilterOptionAndGet,
    FinalModifierOnCaseClass,
    FinalizerWithoutSuper,
    FindAndNotEqualsNoneReplaceWithExists,
    FindDotIsDefined,
    IllegalFormatString,
    ImpossibleOptionSizeCondition,
    IncorrectNumberOfArgsToFormat,
    IncorrectlyNamedExceptions
    InterpolationToString,
    InvalidRegexTest,
    IsInstanceOf,
    LonelySealedTrait,
    LooksLikeInterpolatedString,
    MapGetAndGetOrElse,
    MethodReturningAny,
    NanComparison,
    NullAssignment,
    NullParameter,
    OptionGet,
    OptionSize,
    RepeatedCaseBody,
    RepeatedIfElseBody,
    StripMarginOnRegex,
    SwallowedException,
    TryGet,
    UnnecessaryConversion,
    UnreachableCatch,
    UnsafeContains,
    UnsafeStringContains,
    UnsafeTraversableMethods,
    UnusedMethodParameter,
    VarCouldBeVal,
    VariableShadowing,
    WhileTrue
    # end of Scapegoat rules
]

DisableSyntax.noFinalVal = true
DisableSyntax.noNulls = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noThrow = true
DisableSyntax.noIsInstanceOf = true

OrganizeImports {
  groups = [
    "re:javax?\\."
    "scala."
    "*"
  ]
}
OrganizeImports.targetDialect = Scala3